### ISSUE TITLE
Code Overlap

### ISSUE THREAD

**Issue by ncborcherding** [JuanXie19/LRT_old#1]
Hey Juan Xie, 

I just saw this on Biorxiv! Thanks for building on scRepertoire and a very cool idea on lineage analysis - any chance you could make your LRT compatible and depend on scRepertoire instead of just using the functions directly? I know it might take some work, but a good portion of the underlying code looks to be from scRepertoire and then I can link your repo on the scRepertoire page?

Thanks,
Nick

**Comment by JuanXie19** [comment]
Hi Nick,

Sorry for the late response, and thanks very much for your comments.

As you mentioned, many functions of LRT are based on scRepertoire. Initially, I wanted to directly call scRepertoire, but a little worried that you may actively update scRepertoire. 
For your suggestion, we just submitted the manuscript of LRT, so we may temporarily leave it as it is (just make sure that the package works if the reviewer may try it). If we get back from the reviewer, we'd like to make it compatible and depend on scRepertoire.

**Comment by ncborcherding** [comment]
Sounds great - good luck with the review process and let me know if I can help in any way. 

Nick
